build_dependencies:
  - libaio
dependencies:
  - libaio
targets:
  centos-6:
  centos-7:
env:
  - "LD_LIBRARY_PATH=/tmp/oracle/instantclient_11_1:$LD_LIBRARY_PATH"
  - SKIP_INIT=yes
before_precompile: packaging/before_precompile
